dist: trusty
sudo: false
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
language: node_js
node_js:
- '9'
cache:
  directories:
  - "./node_modules"
install:
- npm install
before_script:
- export CHROME_BIN=chromium-browser
script:
- npm run lint
- xvfb-run -a npm run test -- --single-run --no-progress --browser=ChromeHeadless
- xvfb-run -a npm run e2e -- --no-progress --config=.travis/protractor-ci.conf

deploy:
  provider: script
  skip-cleanup: true
  keep-history: true
  verbose: true
  script: bash .travis/deploy.sh
  on:
    branch: master
