dist: trusty
sudo: false
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
language: node_js
node_js:
- '9'
cache:
  directories:
  - "./node_modules"
install:
- npm install
before_script:
- export CHROME_BIN=chromium-browser
script:
- npm run lint
- xvfb-run -a npm run test -- --single-run --no-progress --browser=ChromeHeadless
- xvfb-run -a npm run e2e -- --no-progress --config=.travis/protractor-ci.conf
deploy:
  skip_cleanup: true
  provider: script
  script:
  - npm run build --prod
  - echo "paulshibanov.com" > dist/CNAME
  - npx angular-cli-ghpages --repo=https://GH_TOKEN@github.com/paulshibanov/blog.git
    --name="Travis deploy bot" --email="info@paulshibanov.com"
  on:
    branch: master
